### PR TITLE
write_install includes duplicate packages

### PR DESCRIPTION
**Pull request by denironyx**
Hi @karthik, this PR addresses issue #43 feel free to check it out and let me know what you think. 

cc @jdblischak

### CODE REVIEW

**Comment by jdblischak** [comment]
@denironyx Great job submitting the PR!

Next step - Update the `write_install()` test to use the new format:

https://github.com/karthik/holepunch/blob/27d0dd1a493400de735859d48955c80113172c23/tests/testthat/test-write_install.R#L45-L52

And confirm the test passes by running:

```
devtools::test(filter = "write_install")
```

**Comment by denironyx** [comment]
Hey @jdblischak, thanks for your suggestions and assistance. 

I have updated the write_install test to the new format.

**Comment by jdblischak** [comment]
@karthik This PR is ready for review

**Comment by karthik** [comment]
Thanks so much @jdblischak 
I'll begin review tomorrow and update the thread.

**Comment by jdblischak** [comment]
@karthik Friendly reminder that this PR is ready for review. Thanks!

**Comment by karthik** [comment]
Thanks @jdblischak Still on my list to complete shortly.

**Comment by karthik** [comment]
Sorry it took so long @denironyx! Please send another PR or just update this thread with name and email so I can add you as a contributor to the package. 🙏

**Comment by denironyx** [comment]
@karthik, thanks for merging this PR. 

name: Dennis Irorere
email: denironyx@gmail.com

**Comment by karthik** [comment]
Thanks Dennis! I added you both as contributors. The package works but builds are failing as I need to update tests. I'll do that soon and the package should be back to being current again.

**Pull request merged**
